export const agencySeedData = [
  {
    id: "reed-recruitment",
    name: "Reed Recruitment",
    address: "Part 1, First Floor, One New Walk, Leicester, LE1 7DD",
    phone: "0116 253 1471",
    email: "leicester@reed.co.uk",
    website: "https://www.reedrecruitment.com",
    linkedIn: "https://www.linkedin.com/company/reed-recruitment",
    latitude: "52.63680000",
    longitude: "-1.13960000",
    description: "Leading recruitment agency with diverse job placements",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "08:30 - 17:30",
      Tuesday: "08:30 - 17:30",
      Wednesday: "08:30 - 17:30",
      Thursday: "08:30 - 17:30",
      Friday: "08:30 - 17:00",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "City Centre",
    recruiters: [
      {
        name: "Sarah Johnson",
        email: "sarah.johnson@reedrecruitment.com",
        specialization: "IT & Engineering",
      },
      {
        name: "Michael Chen",
        email: "michael.chen@reedrecruitment.com",
        specialization: "Finance & Accounting",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "office-angels",
    name: "Office Angels",
    address: "118 Charles Street, Leicester, LE1 1LB",
    phone: "0116 251 3555",
    email: "leicester@officeangels.com",
    website: "https://www.office-angels.com",
    linkedIn: "https://www.linkedin.com/company/office-angels",
    latitude: "52.63540000",
    longitude: "-1.13680000",
    description: "Specialist in office and administrative roles",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "09:00 - 17:30",
      Tuesday: "09:00 - 17:30",
      Wednesday: "09:00 - 17:30",
      Thursday: "09:00 - 17:30",
      Friday: "09:00 - 17:00",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "City Centre",
    recruiters: [
      {
        name: "Emma Wilson",
        email: "emma.wilson@office-angels.com",
        specialization: "Administrative & Office Support",
      },
      {
        name: "David Brown",
        email: "david.brown@office-angels.com",
        specialization: "Secretarial & PA",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "quest-employment",
    name: "Quest Employment",
    address: "13-15 Belvoir Street, Leicester, LE1 6SL",
    phone: "0116 275 7733",
    email: "leicester@questemployment.co.uk",
    website: "https://www.questemployment.co.uk",
    linkedIn: "https://www.linkedin.com/company/quest-employment",
    latitude: "52.62980000",
    longitude: "-1.14220000",
    description: "Professional recruitment services across multiple sectors",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "08:30 - 17:30",
      Tuesday: "08:30 - 17:30",
      Wednesday: "08:30 - 17:30",
      Thursday: "08:30 - 17:30",
      Friday: "08:30 - 16:30",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "City Centre",
    recruiters: [
      {
        name: "Lisa Anderson",
        email: "lisa.anderson@questemployment.co.uk",
        specialization: "Manufacturing & Logistics",
      },
      {
        name: "James Taylor",
        email: "james.taylor@questemployment.co.uk",
        specialization: "Warehouse & Distribution",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "industria-personnel",
    name: "Industria Personnel Services",
    address: "80 Charles Street, Leicester, LE1 1FB",
    phone: null,
    email: "info@industriapersonnel.co.uk",
    website: "https://www.industriapersonnel.co.uk",
    linkedIn: "https://www.linkedin.com/company/industria-personnel",
    latitude: "52.63580000",
    longitude: "-1.13720000",
    description: "Specialized industrial and manufacturing recruitment",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "08:00 - 17:00",
      Tuesday: "08:00 - 17:00",
      Wednesday: "08:00 - 17:00",
      Thursday: "08:00 - 17:00",
      Friday: "08:00 - 16:30",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "City Centre",
    recruiters: [
      {
        name: "Robert Martinez",
        email: "robert.martinez@industriapersonnel.co.uk",
        specialization: "Industrial & Manufacturing",
      },
      {
        name: "Patricia Garcia",
        email: "patricia.garcia@industriapersonnel.co.uk",
        specialization: "Engineering & Technical",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "regional-recruitment",
    name: "Regional Recruitment Services",
    address: "Unit 5, Centre Court Meridian North, Meridian Business Park, Leicester, LE19 1WR",
    phone: "0116 222 2590",
    email: "leicester@regionalrecruitment.co.uk",
    website: "https://www.regionalrecruitment.co.uk",
    linkedIn: "https://www.linkedin.com/company/regional-recruitment-services",
    latitude: "52.58920000",
    longitude: "-1.15260000",
    description: "Regional employment solutions and staffing",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "08:30 - 17:30",
      Tuesday: "08:30 - 17:30",
      Wednesday: "08:30 - 17:30",
      Thursday: "08:30 - 17:30",
      Friday: "08:30 - 17:00",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "Meridian Business Park",
    recruiters: [
      {
        name: "Christopher Lee",
        email: "christopher.lee@regionalrecruitment.co.uk",
        specialization: "Sales & Marketing",
      },
      {
        name: "Jennifer White",
        email: "jennifer.white@regionalrecruitment.co.uk",
        specialization: "Customer Service & Retail",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "macildowie",
    name: "Macildowie Recruitment and Retention",
    address: "3 Merus Court Meridian Way, Leicester, LE19 1WY",
    phone: "0116 222 2590",
    email: "leicester@macildowie.co.uk",
    website: "https://www.macildowie.com",
    linkedIn: "https://www.linkedin.com/company/macildowie-recruitment",
    latitude: "52.58950000",
    longitude: "-1.15420000",
    description: "Executive and professional recruitment",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "08:30 - 17:30",
      Tuesday: "08:30 - 17:30",
      Wednesday: "08:30 - 17:30",
      Thursday: "08:30 - 17:30",
      Friday: "08:30 - 16:30",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "Meridian Business Park",
    recruiters: [
      {
        name: "Andrew Harris",
        email: "andrew.harris@macildowie.com",
        specialization: "Professional & Management",
      },
      {
        name: "Victoria Thompson",
        email: "victoria.thompson@macildowie.com",
        specialization: "Executive & Senior Roles",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "sf-recruitment",
    name: "SF Recruitment",
    address: "Watling Suite, High Cross Business Park, Sharnford, East Midlands, LE10 3PG",
    phone: "0116 281 6670",
    email: "info@sfrecruitment.co.uk",
    website: "https://www.sfrecruitment.co.uk",
    linkedIn: "https://www.linkedin.com/company/sf-recruitment",
    latitude: "52.56450000",
    longitude: "-1.21340000",
    description: "Specialist recruitment for various industries",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "09:00 - 17:30",
      Tuesday: "09:00 - 17:30",
      Wednesday: "09:00 - 17:30",
      Thursday: "09:00 - 17:30",
      Friday: "09:00 - 17:00",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "Sharnford Area",
    recruiters: [
      {
        name: "Nicholas Clark",
        email: "nicholas.clark@sfrecruitment.co.uk",
        specialization: "Hospitality & Catering",
      },
      {
        name: "Sophie Robinson",
        email: "sophie.robinson@sfrecruitment.co.uk",
        specialization: "Hotel & Tourism",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "accept-recruitment",
    name: "Accept Recruitment",
    address: "121 Barkby Rd, Leicester, LE4 9LU",
    phone: "0116 218 2133",
    email: "leicester@acceptrecruitment.co.uk",
    website: "https://www.acceptrecruitment.co.uk",
    linkedIn: "https://www.linkedin.com/company/accept-recruitment",
    latitude: "52.65120000",
    longitude: "-1.10980000",
    description: "Comprehensive recruitment and staffing solutions",
    services: null,
    documentsRequired: null,
    openingHours: {
      Monday: "08:00 - 17:00",
      Tuesday: "08:00 - 17:00",
      Wednesday: "08:00 - 17:00",
      Thursday: "08:00 - 17:00",
      Friday: "08:00 - 16:00",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    region: "Barkby Road Area",
    recruiters: [
      {
        name: "Daniel Walker",
        email: "daniel.walker@acceptrecruitment.co.uk",
        specialization: "General Staffing & Recruitment",
      },
      {
        name: "Rebecca Scott",
        email: "rebecca.scott@acceptrecruitment.co.uk",
        specialization: "Temporary & Permanent Placements",
      },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
];
